export const USER_SET_CURRENT = 'USER_SET_CURRENT';
export const USER_SET_CURRENT_FAIL = 'USER_SET_CURRENT_ERROR';
export const STORY_CREATE_SUCCESS = 'STORY_CREATE_SUCCESS';
export const STORIES_FETCH_SUCCESS = 'STORIES_FETCH_SUCCESS';
export const STORY_FETCH_SUCCESS = 'STORY_FETCH_SUCCESS';
export const STORY_REVIEW_SUCCESS = 'STORY_REVIEW_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
